# Dependencies
markdown:         redcarpet
highlighter:      false

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Sokolskaya Translations
title_russian:    Евгения Сокольская
tagline:          'Russian to English translation'
tagline_russian:  'Перевод с русского на английский'
description:      'Your choice for Russian to English translation.'
description_russian: 'Сертифицированный перевод с русского на английский'
url:              http://sokolskayatranslations.com
baseurl:          /

author:
  name:           'Eugenia Sokolskaya'
  url:            http://sokolskayatranslations.com
  email:          eugenia@sokolskayatranslations.com

paginate:         5

# Custom vars
version:          2.1.0

gems: [jekyll-paginate]

github:
  repo:           https://github.com/geniasokol/geniasokol.github.io
